# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'lbta-instagram-firebase' do
  # Comment the next line if you don't want to use dynamic frameworks
  # To run on Robbie's iPhone: turn off frameworks, add -> :modular_headers => true 
  # use_frameworks!

  # Pods for lbta-instagram-firebase
pod 'Firebase/Core', :modular_headers => true 
pod 'Firebase/Auth', :modular_headers => true 
pod 'Firebase/Database', :modular_headers => true 
pod 'Firebase/Storage', :modular_headers => true 
pod 'FirebaseFirestore', :modular_headers => true 

end
