# Uncomment the next line to define a global platform for your project
# platform :iOS, '13.2'

target 'testSinglePage' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for testSinglePage
  pod "TinyConstraints"

end
